# SPDX-FileCopyrightText: 2021 René de Hesselle <dehesselle@web.de>
#
# SPDX-License-Identifier: MIT

stages:
  - build
  - release

variables:
  GIT_DEPTH: 1
  GIT_SUBMODULE_STRATEGY: recursive
  CCACHE_VERSION: "4.6.1"
  CMAKE_VERSION: "3.21.1"

#------------------------------------------------------------------------- build

build:
  stage: build
  parallel:
    matrix:
      - RUNNER: [ "macosintel", "macosarm" ]
  rules:
    - if: $RUNNER == "macosintel"
      variables:
        SDKROOT: /opt/sdks/MacOSX10.11.4.sdk
    - if: $RUNNER == "macosarm"
      variables:
        SDKROOT: /opt/sdks/MacOSX11.3.sdk
  tags:
    - ${RUNNER}
  variables:
    CMAKE_URL: https://github.com/Kitware/CMake/releases/download/v$CMAKE_VERSION/cmake-$CMAKE_VERSION-macos-universal.tar.gz
    CCACHE_URL: https://github.com/ccache/ccache/releases/download/v$CCACHE_VERSION/ccache-$CCACHE_VERSION.tar.xz
  script:
    - curl -L $CMAKE_URL  | tar -C $CI_PROJECT_DIR -xz
    - curl -L $CCACHE_URL | tar -C $CI_PROJECT_DIR -xJ
    - mkdir build; cd build
    - $CI_PROJECT_DIR/$(basename -s .tar.gz $CMAKE_URL)/CMake.app/Contents/bin/cmake
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_GENERATOR="Unix Makefiles"
        -DCMAKE_INSTALL_PREFIX=$CI_PROJECT_DIR/install
        -DZSTD_FROM_INTERNET=ON
        -DHIREDIS_FROM_INTERNET=ON
        $CI_PROJECT_DIR/ccache-$CCACHE_VERSION
    - make -j$(sysctl -n hw.ncpu)
    - make install
    - tar -C $CI_PROJECT_DIR/install/bin -cpJf $CI_PROJECT_DIR/ccache_$(uname -m).tar.xz ccache
  artifacts:
    paths:
      - ccache_*.tar.xz

#----------------------------------------------------------------------- release

release:
  stage: release
  only:
    - tags
  image: python:3-alpine
  script:
    - pip3 install gitlab-release==5.6
    - gitlab-release ccache_*.tar.xz
