# SPDX-FileCopyrightText: 2021 René de Hesselle <dehesselle@web.de>
#
# SPDX-License-Identifier: MIT

name: build
on:
  push:
    branches:
      - '*'
  workflow_call:
env:
  CCACHE_VERSION: 4.7.4
  BUILD_DIR: ${{ github.workspace }}/build
  INSTALL_DIR: ${{ github.workspace }}/install

jobs:

################################################################################

  build:
    runs-on: macos-12
    strategy:
      matrix:
        arch: [x86_64, arm64]
    steps:

      #----------------------------------------------------------------- prepare

      - name: install Ninja
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1
          HOMEBREW_NO_INSTALL_CLEANUP: 1
        run: brew install ninja

      #------------------------------------------------------------------- build

      - name: download source
        run: curl -L https://github.com/ccache/ccache/releases/download/v$CCACHE_VERSION/ccache-$CCACHE_VERSION.tar.xz | tar -xJp

      - name: build ccache
        env:
          CMAKE_GENERATOR: Ninja
        run: |
          mkdir $BUILD_DIR
          cd $BUILD_DIR
          cmake \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR \
            -DCMAKE_OSX_ARCHITECTURES="${{ matrix.arch }}" \
            -DCMAKE_OSX_DEPLOYMENT_TARGET="10.15" \
            -DCMAKE_SYSTEM_PROCESSOR="${{ matrix.arch }}" \
            -DZSTD_FROM_INTERNET=ON \
            -DHIREDIS_FROM_INTERNET=ON \
            ../ccache-$CCACHE_VERSION
          cmake --build .
          ls -lah

      #---------------------------------------------------------------- artifact

