# SPDX-License-Identifier: MIT
#
# This file is part of https://github.com/dehesselle/ccache_macos

name: build
on: push
env:
  CCACHE_VERSION: 4.2
  BUILD_DIR: ${{ github.workspace }}/build
  INSTALL_DIR: ${{ github.workspace }}/install
jobs:

################################################################################

  build:
    runs-on: macos-10.15
    steps:

    #------------------------------------------------------------------- prepare

    # GitHub does not provide old SDKs like 10.11 (from Xcode 7.3.1). There is
    # no official public download available from Apple and I don't trust 3rd
    # party sources (e.g. "phracker"), so I'm enabling this job to download
    # a compressed tarball that contains the SDK.
    # In order to use this, you need to setup a repository secret named
    # SDK_DOWNLOAD_URL and give a link to a .tar.xz file.
    - name: install macOS SDK
      env:
        SDK_DOWNLOAD_URL: ${{ secrets.SDK_DOWNLOAD_URL }}
      if: env.SDK_DOWNLOAD_URL != null
      run: |
        curl -L ${{ secrets.SDK_DOWNLOAD_URL }} | tar -xJp
        echo "SDKROOT=$GITHUB_WORKSPACE/$(basename ${SDK_DOWNLOAD_URL%%.tar.xz*})" >> $GITHUB_ENV

    - name: install Ninja
      env:
        HOMEBREW_NO_AUTO_UPDATE: 1
        HOMEBREW_NO_INSTALL_CLEANUP: 1
      run: brew install ninja

    #--------------------------------------------------------------------- build

    - name: download source
      run: curl -L https://github.com/ccache/ccache/releases/download/v$CCACHE_VERSION/ccache-$CCACHE_VERSION.tar.xz | tar -xJp

    - name: build ccache
      env:
        CMAKE_GENERATOR: Ninja
      run: |
        mkdir $BUILD_DIR
        cd $BUILD_DIR
        cmake -DCMAKE_BUILD_TYPE=Release -DZSTD_FROM_INTERNET=ON -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR ../ccache-$CCACHE_VERSION
        ninja
        ninja install

    #------------------------------------------------------------------ artifact

    - name: generate checksum
      run: |
        cd $INSTALL_DIR/bin
        shasum -a 256 ccache > ccache.sha256

    - name: upload workflow artifact
      uses: actions/upload-artifact@v2
      with:
        name: ccache
        path: ${{ env.INSTALL_DIR }}/bin/*

################################################################################

  release:
    runs-on: macos-10.15
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    steps:

    - name: download build artifact
      uses: actions/download-artifact@v2
      with:
        name: ccache

    - name: create release archive
      run: tar cpJf ccache.tar.xz ccache ccache.sha256

    - name: create release
      id: release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: true
        prerelease: false

    - name: upload ccache archive to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        #hirse: archive machen vom bin direkt
        # erst hier nennen wir die versionnummer rein
        # das verbessern wir auch an mibap: kein bedarf für versionsnummer
        # hier, wir nehmen das Tag
        asset_path: ccache.tar.xz
        asset_name: ccache_${{ github.ref }}.tar.xz
        asset_content_type: application/octet-stream
